# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? By default Typo CI will select 'en' & 'en_GB'
# Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# nl
# pt
# pt_BR
# tr
dictionaries:
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".github/*"
  - ".git/*"

# Any words we should ignore?
excluded_words:
  - dto
  - sln
  - moq
  - authorize
  - unauthorized
  - behavior
  - color
  - colors
  - center
  - normalize
  - serialize
  - humanize
  - colorful
  - artifact
  - CONTINE
  - MediatR
  - rpldy
  - Uploady
  - usings

  

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true