name: Build & Deploy Application

on:
  push:
    branches: [ master, main ]



jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

  Development:
      runs-on: ubuntu-latest
      needs: Build
      name: Non-Prod
      environment: Non-Prod
      steps:
      - uses: actions/download-artifact@v2
        with:
          name: app
          path: app

  Production:
      runs-on: ubuntu-latest
      needs: Development
      environment: Production
      steps:
      - uses: actions/download-artifact@v2
        with:
          name: app
          path: app
