name: Build & Deploy Application

on:
  push:
    branches: [ master, main ]



jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

  Development:
      runs-on: ubuntu-latest
      needs: Build
      name: Non-Prod
      environment: Non-Prod
      steps:
      - name: Verify the workspace context
        run: echo 'Workspace directory is ${{ github.workspace }}'

  Production:
      runs-on: ubuntu-latest
      needs: Development
      environment: Production
      steps:
      - name: Verify the workspace context
        run: echo 'Workspace directory is ${{ github.workspace }}'
